on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:

    - name: create sample one test file
      run: |
        pwd
        touch testfile.before-docker
        ls

    - name: Hello world action step
      id: hello
      uses: meatlink/sandbox_gh_action@master
      with:
        who-to-greet: 'Mona the Octocat'

    - name: create sample another test file
      run: |
        pwd
        touch testfile.after-docker
        ls
  
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"

